"use client"
import Link from "next/link"
import { Badge } from "@/components/ui/badge"
import { Card } from "@/components/ui/card"
import { MapPin, DollarSign, Globe, ExternalLink, Building2 } from "lucide-react"
export function JobCard({ job }: { job: any }) {
  const daysAgo = Math.floor((Date.now()-new Date(job.posted_at).getTime())/86400000)
  const salary = job.salary_min&&job.salary_max?`$${(job.salary_min/1000).toFixed(0)}k-$${(job.salary_max/1000).toFixed(0)}k`:"Salary N/A"
  const shortDesc = (job.description||"").length>200?job.description.substring(0,200)+"...":job.description
  return <Card className="p-5 hover:shadow-lg transition-shadow"><div className="flex items-start gap-4"><div>{job.company_logo_url?<img src={job.company_logo_url} alt={job.company_name} className="w-14 h-14 object-contain rounded-lg bg-gray-50"/>:<div className="w-14 h-14 rounded-lg bg-blue-100 flex items-center justify-center"><Building2 className="w-7 h-7 text-blue-600"/></div>}</div><div className="flex-1 min-w-0"><div className="flex items-start justify-between gap-2"><div><Link href={`/job/${job.id}`} className="text-lg font-semibold text-blue-600 hover:underline line-clamp-1">{job.title}</Link><p className="text-gray-700 font-medium mt-0.5">{job.company_name}</p></div><span className="text-xs text-gray-400 flex-shrink-0">{daysAgo===0?"Today":`${daysAgo}d ago`}</span></div><div className="flex flex-wrap gap-2 mt-2"><Badge variant="secondary" className="flex items-center gap-1"><MapPin className="w-3 h-3"/>{job.location}</Badge>{job.remote&&<Badge className="flex items-center gap-1"><Globe className="w-3 h-3"/>Remote</Badge>}<Badge variant="outline"><DollarSign className="w-3 h-3"/>{salary}</Badge>{job.seniority&&<Badge variant="secondary">{job.seniority}</Badge>}</div><p className="text-gray-600 text-sm mt-3 line-clamp-2">{shortDesc}</p>{job.technologies?.length>0&&<div className="flex flex-wrap gap-1.5 mt-3">{job.technologies.slice(0,5).map((t:string)=> <span key={t} className="text-xs bg-gray-100 text-gray-600 px-2 py-1 rounded-md">{t}</span>)}{job.technologies.length>5&&<span className="text-xs text-gray-400">+{job.technologies.length-5}</span>}</div>}<div className="flex gap-3 mt-4"><a href={job.url} target="_blank" className="inline-flex items-center gap-1.5 bg-blue-600 text-white text-sm px-4 py-2 rounded-md hover:bg-blue-700 font-medium">Apply <ExternalLink className="w-3.5 h-3.5"/></a><Link href={`/job/${job.id}`} className="inline-flex items-center gap-1.5 border border-gray-300 text-gray-700 text-sm px-4 py-2 rounded-md hover:bg-gray-50">Details</Link></div></div></div></Card>
}