import Link from "next/link"
import { getJobById } from "@/lib/theirstack"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card } from "@/components/ui/card"
import { MapPin, DollarSign, Clock, Globe, ExternalLink, ArrowLeft, Building2 } from "lucide-react"
export default async function JobDetailPage({ params }: { params: { id: string } }) {
  const job = await getJobById(params.id)
  if (!job) return <main className="max-w-4xl mx-auto px-4 py-16 text-center"><h1 className="text-2xl font-bold mb-4">Job Not Found</h1><p className="text-gray-600 mb-8">This job may have expired.</p><Link href="/jobs"><Button>Back to Search</Button></Link></main>
  const daysAgo = Math.floor((Date.now() - new Date(job.posted_at).getTime()) / 86400000)
  const salaryDisplay = job.salary_min && job.salary_max ? `$${(job.salary_min/1000).toFixed(0)}k - $${(job.salary_max/1000).toFixed(0)}k` : "Salary not disclosed"
  return <main className="max-w-4xl mx-auto px-4 py-8"><Link href="/jobs" className="inline-flex items-center gap-2 text-gray-600 hover:text-blue-600 mb-6"><ArrowLeft className="w-4 h-4" /> Back to search</Link><Card className="p-8"><div className="flex items-start gap-5 mb-6"><div className="flex-shrink-0">{job.company_logo_url ? <img src={job.company_logo_url} alt={job.company_name} className="w-16 h-16 object-contain rounded-lg bg-gray-50" /> : <div className="w-16 h-16 rounded-lg bg-blue-100 flex items-center justify-center"><Building2 className="w-8 h-8 text-blue-600" /></div>}</div><div><h1 className="text-2xl font-bold text-gray-900">{job.title}</h1><p className="text-lg text-gray-700 mt-1">{job.company_name}</p></div></div><div className="flex flex-wrap gap-2 mb-6"><Badge variant="secondary" className="flex items-center gap-1"><MapPin className="w-3 h-3" />{job.location}</Badge>{job.remote && <Badge><Globe className="w-3 h-3" />Remote</Badge>}<Badge variant="outline"><DollarSign className="w-3 h-3" />{salaryDisplay}</Badge><Badge variant="secondary"><Clock className="w-3 h-3" />{daysAgo === 0 ? "Today" : `${daysAgo}d ago`}</Badge>{job.seniority && <Badge variant="secondary">{job.seniority}</Badge>}</div>{job.technologies?.length > 0 && <div className="flex flex-wrap gap-2 mb-6">{job.technologies.map((t: string) => <span key={t} className="text-sm bg-gray-100 px-3 py-1 rounded-md">{t}</span>)}</div>}<div className="prose max-w-none mb-8"><h2 className="text-xl font-semibold mb-3">Description</h2><div className="text-gray-700 whitespace-pre-wrap">{job.description}</div></div><div className="flex gap-4"><a href={job.url} target="_blank" className="inline-flex items-center gap-2 bg-blue-600 text-white px-6 py-3 rounded-lg hover:bg-blue-700 font-medium">Apply <ExternalLink className="w-4 h-4" /></a></div></Card></main>
}